/* FireShield AI — Sample Data for Dashboard */
const SAMPLE_INCIDENTS = [
    { id: "INC-1001", title: "Factory Fire at Manesar Industrial Area", description: "Major industrial fire in factory unit. Chemical storage nearby. Workers trapped on second floor.", latitude: 28.3590, longitude: 76.9366, address: "IMT Manesar, Gurgaon, Haryana", category: "industrial", severity: 5, status: "en_route", assigned_team: "Alpha Team", response_time_mins: 6.5, created_at: "2025-06-28T10:15:00Z", ai_analysis: { severity_score: 4.8, fire_type: "Industrial/Chemical Fire", risk_level: "CRITICAL", estimated_affected_area: "2000 sq meters", recommended_units: 6, analysis_text: "Critical industrial fire with chemical hazard. Immediate multi-unit response required.", confidence_score: 0.92 }},
    { id: "INC-1002", title: "Residential Building Fire in Lajpat Nagar", description: "Fire broke out on 4th floor of apartment building. Smoke spreading to upper floors.", latitude: 28.5700, longitude: 77.2370, address: "Block C, Lajpat Nagar II, New Delhi", category: "building", severity: 4, status: "assigned", assigned_team: "Bravo Team", response_time_mins: 8.2, created_at: "2025-06-27T14:30:00Z", ai_analysis: { severity_score: 3.9, fire_type: "Residential Building Fire", risk_level: "HIGH", estimated_affected_area: "400 sq meters", recommended_units: 3, analysis_text: "High-severity residential fire. Evacuate upper floors immediately.", confidence_score: 0.88 }},
    { id: "INC-1003", title: "Kitchen Fire in Andheri Restaurant", description: "Kitchen grease fire in restaurant during peak hours.", latitude: 19.1136, longitude: 72.8697, address: "Andheri West, Mumbai", category: "kitchen", severity: 2, status: "resolved", assigned_team: "Charlie Team", response_time_mins: 5.0, created_at: "2025-06-26T19:45:00Z", ai_analysis: { severity_score: 2.1, fire_type: "Kitchen/Domestic Fire", risk_level: "LOW", estimated_affected_area: "30 sq meters", recommended_units: 1, analysis_text: "Minor kitchen fire. Standard response protocol.", confidence_score: 0.91 }},
    { id: "INC-1004", title: "Electrical Fire at Koramangala Office", description: "Short circuit fire in server room of IT office.", latitude: 12.9352, longitude: 77.6245, address: "5th Block, Koramangala, Bangalore", category: "electrical", severity: 3, status: "resolved", assigned_team: "Delta Team", response_time_mins: 7.3, created_at: "2025-06-25T09:20:00Z", ai_analysis: { severity_score: 3.0, fire_type: "Electrical Fire", risk_level: "MODERATE", estimated_affected_area: "100 sq meters", recommended_units: 2, analysis_text: "Electrical fire in server room. Cut power supply immediately.", confidence_score: 0.85 }},
    { id: "INC-1005", title: "Warehouse Fire in Ambattur", description: "Textile warehouse caught fire. Flammable materials.", latitude: 13.1143, longitude: 80.1548, address: "Ambattur Industrial Estate, Chennai", category: "industrial", severity: 5, status: "arrived", assigned_team: "Alpha Team", response_time_mins: 9.1, created_at: "2025-06-24T11:00:00Z", ai_analysis: { severity_score: 4.6, fire_type: "Industrial Warehouse Fire", risk_level: "CRITICAL", estimated_affected_area: "1500 sq meters", recommended_units: 5, analysis_text: "Critical warehouse fire with flammable materials.", confidence_score: 0.90 }},
    { id: "INC-1006", title: "Forest Fire in Bandipur", description: "Forest fire in eastern section. Dry conditions.", latitude: 11.6700, longitude: 76.6300, address: "Bandipur National Park, Karnataka", category: "forest", severity: 4, status: "en_route", assigned_team: "Forest Unit", response_time_mins: 15.0, created_at: "2025-06-23T06:30:00Z", ai_analysis: { severity_score: 3.8, fire_type: "Forest/Wildfire", risk_level: "HIGH", estimated_affected_area: "5000 sq meters", recommended_units: 5, analysis_text: "Forest fire spreading due to dry conditions.", confidence_score: 0.82 }},
    { id: "INC-1007", title: "Gas Leak Fire at Chandni Chowk", description: "LPG cylinder explosion in market. Multiple shops affected.", latitude: 28.6506, longitude: 77.2302, address: "Chandni Chowk, Old Delhi", category: "gas_leak", severity: 4, status: "arrived", assigned_team: "Bravo Team", response_time_mins: 5.5, created_at: "2025-06-22T16:45:00Z", ai_analysis: { severity_score: 4.0, fire_type: "Gas Leak Fire", risk_level: "HIGH", estimated_affected_area: "300 sq meters", recommended_units: 4, analysis_text: "Gas leak explosion in densely populated market.", confidence_score: 0.87 }},
    { id: "INC-1008", title: "Vehicle Fire on NH-48", description: "Chemical truck fire on expressway.", latitude: 28.4595, longitude: 77.0266, address: "NH-48, Gurgaon", category: "vehicle", severity: 3, status: "resolved", assigned_team: "Highway Rescue", response_time_mins: 12.0, created_at: "2025-06-21T22:10:00Z", ai_analysis: { severity_score: 2.8, fire_type: "Vehicle Fire", risk_level: "MODERATE", estimated_affected_area: "20 sq meters", recommended_units: 2, analysis_text: "Chemical truck fire. Hazmat response needed.", confidence_score: 0.84 }},
    { id: "INC-1009", title: "Mall Fire in Salt Lake City", description: "Smoke detected in food court, 3rd floor.", latitude: 22.5806, longitude: 88.4137, address: "City Centre, Salt Lake, Kolkata", category: "building", severity: 3, status: "acknowledged", assigned_team: null, response_time_mins: null, created_at: "2025-06-20T13:25:00Z", ai_analysis: { severity_score: 3.2, fire_type: "Commercial Fire", risk_level: "MODERATE", estimated_affected_area: "200 sq meters", recommended_units: 3, analysis_text: "Mall fire with mass evacuation potential.", confidence_score: 0.86 }},
    { id: "INC-1010", title: "Hospital Generator Fire", description: "Generator room fire in hospital basement.", latitude: 17.4325, longitude: 78.4073, address: "Jubilee Hills, Hyderabad", category: "electrical", severity: 4, status: "assigned", assigned_team: "Echo Team", response_time_mins: 4.2, created_at: "2025-06-19T08:50:00Z", ai_analysis: { severity_score: 4.1, fire_type: "Hospital Fire", risk_level: "CRITICAL", estimated_affected_area: "150 sq meters", recommended_units: 4, analysis_text: "Hospital fire — patient safety critical priority.", confidence_score: 0.93 }},
    { id: "INC-1011", title: "Slum Fire in Dharavi", description: "Fire spread across shanties. Dense area.", latitude: 19.0434, longitude: 72.8550, address: "Dharavi, Mumbai", category: "building", severity: 5, status: "arrived", assigned_team: "Alpha Team", response_time_mins: 7.8, created_at: "2025-06-18T04:15:00Z", ai_analysis: { severity_score: 4.7, fire_type: "Slum/Dense Area Fire", risk_level: "CRITICAL", estimated_affected_area: "3000 sq meters", recommended_units: 7, analysis_text: "Critical fire in dense slum area. Access challenges.", confidence_score: 0.89 }},
    { id: "INC-1012", title: "College Lab Fire at IIT Delhi", description: "Chemical lab fire. Students evacuated.", latitude: 28.5450, longitude: 77.1926, address: "IIT Delhi, Hauz Khas", category: "electrical", severity: 3, status: "resolved", assigned_team: "Campus Team", response_time_mins: 3.5, created_at: "2025-06-17T11:30:00Z", ai_analysis: { severity_score: 2.9, fire_type: "Laboratory Fire", risk_level: "MODERATE", estimated_affected_area: "50 sq meters", recommended_units: 2, analysis_text: "Lab fire contained. Chemical safety check required.", confidence_score: 0.87 }},
    { id: "INC-1013", title: "Godown Fire in MIDC Pune", description: "Plastic raw material godown. Toxic fumes.", latitude: 18.5904, longitude: 73.7395, address: "MIDC Bhosari, Pune", category: "industrial", severity: 4, status: "en_route", assigned_team: "Charlie Team", response_time_mins: 10.5, created_at: "2025-06-16T15:40:00Z", ai_analysis: { severity_score: 4.2, fire_type: "Industrial Godown Fire", risk_level: "HIGH", estimated_affected_area: "1000 sq meters", recommended_units: 4, analysis_text: "Toxic fumes — evacuate surrounding area.", confidence_score: 0.88 }},
    { id: "INC-1014", title: "Temple Fire during Festival", description: "Decorative fire spread at temple.", latitude: 26.9124, longitude: 75.7873, address: "Govind Dev Ji Temple, Jaipur", category: "other", severity: 3, status: "resolved", assigned_team: "Jaipur Fire", response_time_mins: 6.0, created_at: "2025-06-15T20:00:00Z", ai_analysis: { severity_score: 2.8, fire_type: "Festive/Decorative Fire", risk_level: "MODERATE", estimated_affected_area: "100 sq meters", recommended_units: 2, analysis_text: "Festival fire. Crowd management needed.", confidence_score: 0.83 }},
    { id: "INC-1015", title: "Hostel Kitchen Fire at JNU", description: "Minor kitchen fire in hostel mess.", latitude: 28.5402, longitude: 77.1674, address: "JNU Campus, New Delhi", category: "kitchen", severity: 1, status: "resolved", assigned_team: null, response_time_mins: 2.0, created_at: "2025-06-14T07:20:00Z", ai_analysis: { severity_score: 1.5, fire_type: "Kitchen Fire", risk_level: "LOW", estimated_affected_area: "15 sq meters", recommended_units: 1, analysis_text: "Minor kitchen fire. Self-contained.", confidence_score: 0.94 }},
    { id: "INC-1016", title: "Construction Site Fire in Noida", description: "Under-construction high-rise materials caught fire.", latitude: 28.5355, longitude: 77.3910, address: "Sector 150, Noida, UP", category: "building", severity: 2, status: "resolved", assigned_team: "Noida Fire", response_time_mins: 8.0, created_at: "2025-06-13T12:55:00Z", ai_analysis: { severity_score: 2.3, fire_type: "Construction Site Fire", risk_level: "LOW", estimated_affected_area: "200 sq meters", recommended_units: 2, analysis_text: "Construction material fire. No occupants.", confidence_score: 0.90 }},
    { id: "INC-1017", title: "Bus Depot Fire in Nehru Place", description: "DTC bus caught fire at depot.", latitude: 28.5491, longitude: 77.2538, address: "Nehru Place, New Delhi", category: "vehicle", severity: 3, status: "assigned", assigned_team: "Bravo Team", response_time_mins: 5.8, created_at: "2025-06-12T17:30:00Z", ai_analysis: { severity_score: 3.1, fire_type: "Vehicle/Bus Fire", risk_level: "MODERATE", estimated_affected_area: "100 sq meters", recommended_units: 2, analysis_text: "Bus fire. Fuel tank risk. Move adjacent vehicles.", confidence_score: 0.86 }},
    { id: "INC-1018", title: "Firecracker Warehouse Fire", description: "Illegal firecracker storage. Multiple explosions.", latitude: 13.0827, longitude: 80.2707, address: "Sivakasi Warehouse, Chennai", category: "industrial", severity: 5, status: "en_route", assigned_team: "Delta Team", response_time_mins: 11.0, created_at: "2025-06-11T23:45:00Z", ai_analysis: { severity_score: 4.9, fire_type: "Explosive Storage Fire", risk_level: "CRITICAL", estimated_affected_area: "3000 sq meters", recommended_units: 8, analysis_text: "Explosive materials. 500m evacuation radius.", confidence_score: 0.91 }},
];

const SAMPLE_TEAMS = [
    { name: "Alpha Team", status: "on_scene", members: 8, vehicle: "Fire Engine + Ladder Truck", assignment: "INC-1001: Factory Fire, Manesar", color: "#ef4444", stats: { missions: 42, avgResponse: "5.2 min", rating: "4.8/5" }},
    { name: "Bravo Team", status: "en_route", members: 6, vehicle: "Fire Engine", assignment: "INC-1002: Building Fire, Lajpat Nagar", color: "#3b82f6", stats: { missions: 38, avgResponse: "6.1 min", rating: "4.7/5" }},
    { name: "Charlie Team", status: "available", members: 6, vehicle: "Fire Engine + Rescue Van", assignment: null, color: "#22c55e", stats: { missions: 35, avgResponse: "5.8 min", rating: "4.6/5" }},
    { name: "Delta Team", status: "on_scene", members: 7, vehicle: "Fire Engine + Water Tanker", assignment: "INC-1018: Firecracker Warehouse, Chennai", color: "#f97316", stats: { missions: 40, avgResponse: "5.5 min", rating: "4.9/5" }},
    { name: "Echo Team", status: "available", members: 5, vehicle: "Rescue Van", assignment: null, color: "#8b5cf6", stats: { missions: 28, avgResponse: "6.8 min", rating: "4.5/5" }},
    { name: "Forest Response Unit", status: "en_route", members: 10, vehicle: "Wildfire Response Vehicle", assignment: "INC-1006: Forest Fire, Bandipur", color: "#22c55e", stats: { missions: 15, avgResponse: "12.0 min", rating: "4.7/5" }},
];

const FIRE_STATIONS = [
    { name: "Delhi Fire Service HQ", lat: 28.6328, lng: 77.2197 },
    { name: "Mumbai Central Fire Station", lat: 18.9690, lng: 72.8311 },
    { name: "Bangalore City Fire Station", lat: 12.9784, lng: 77.5719 },
    { name: "Chennai Central Fire Station", lat: 13.0827, lng: 80.2707 },
    { name: "Kolkata Fire Brigade HQ", lat: 22.5726, lng: 88.3639 },
    { name: "Hyderabad Fire Station", lat: 17.3850, lng: 78.4867 },
    { name: "Pune Fire Brigade", lat: 18.5204, lng: 73.8567 },
    { name: "Jaipur Fire Station", lat: 26.9124, lng: 75.7873 },
];
